name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo or code
        uses: actions/checkout@v2

      - name: Log in to Heroku Container Registry
        run: echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Build docker image
        run: docker build -t my-java-app:latest .
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: 138.197.14.202
            username: root
            key: ${{ secrets.DO_PRIVATE_KEY }}
            port: 22
            script: whoami
