name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo or code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t my-java-app:latest .

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: 138.197.14.202
            username: root
            key: ${{ secrets.DO_PRIVATE_KEY }}
            port: 22
            script: | #cat /root/akhilTest/akhilTest.yml
                     whoami
                     pwd
                     mkdir Github_to_Droplet
                     cd Github_to_Droplet
                     touch test.yml
                     cat <<EOF > test.yml
                     Hello! The connection from Github to Droplet is Successfull!
                     EOF
                     cat test.yml
                     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                     docker pull akhil7199/my-java-app:fa878d2
                     docker run -t -d akhil7199/my-java-app:fa878d2